export const FETCHING_CATEGORIES_START = 'FETCHING_CATEGORIES_START';
export const FETCHING_CATEGORIES_SUCCESS = 'FETCHING_CATEGORIES_SUCCESS';
export const FETCHING_CATEGORIES_FAILURE = 'FETCHING_CATEGORIES_FAILURE';
export const CHECK_FILTER_CATEGORY = 'CHECK_FILTER_CATEGORY';
export const CLEAR_SELECTED_CATEGORIES = 'CLEAR_SELECTED_CATEGORIES';
